### ISSUE TITLE
Python type management throws exceptions with Python 3.6

### ISSUE THREAD

**Issue by ThomasG77** [JanCaha/qgis-plugin-bivariate-renderer#1]
`from __future__ import annotations` fails when using QGIS that use a Python 3.6.
So, the plugin is only compatible for QGIS Python installation with Python 3.7 at least.

No backward compatible solution according to https://stackoverflow.com/questions/52889746/cant-import-annotations-from-future/52890129

**Comment by JanCaha** [comment]
Hm...that's not good. But I am using at least one function that requires QGIS 3.20 IIRC (which bundles Python 3.9 at least for Windows) and security support for [Python 3.7 ends in 3 months anyways](https://endoflife.date/python). So it seems, that it would be better to use never version of Python. I think that I may leave this as it is.

**Comment by nyalldawson** [comment]
Qgis 3.20 mandates python 3.7+ anyway, so setting the min version as 3.20 implies this requirement.
