### ISSUE TITLE
ModuleNotFoundError: No module named 'BivariateRenderer.text_constants' 

### ISSUE THREAD

**Issue by ljegou** [JanCaha/qgis-plugin-bivariate-renderer#2]
With Python 3.8 on MacOS, the extension downloads but fail to install.

Error msg : 

  File "/Users/laurentjegou/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/BivariateRenderer/renderer/bivariate_renderer.py", line 17, in 
    from ..text_constants import Texts
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'BivariateRenderer.text_constants'

Version de Python : 3.8.7 (default, May 24 2021, 13:02:34) [Clang 12.0.5 (clang-1205.0.22.9)] 
Version de QGIS : 3.20.2-Odense Odense, 9f59a15664 

A colleague on Windows 10 / QGIS 3.20.3 has the same problem.

Thanks for your work, it'll be a very useful extension :)

LJ

**Comment by JanCaha** [comment]
Do you have the latest version - 0.2.1? Please try upgrading the plugin. This error was in the first version (0.2), I found it rather quickly after publishing it and released an update with the fix later that day.  

I looked through the code and the bad import is not anywhere in the code, so it should be ok in this latest version.

**Comment by kalab-oto** [comment]
Can reproduce here (version 0.2.1).

It is caused by the `BivariateRenderer/text_constants.py` file is not included in the package in QGIS plugin repository ;).

**Comment by ljegou** [comment]
I'm using the 0.2.1 version, from the plugins manager inside QGIS.

**Comment by JanCaha** [comment]
My bad...I found the first error, but there as another one right after that. 

The 0.2.2 version is online and should fix it.

**Comment by ljegou** [comment]
Yes ! It works beautifully now, thanks :)
